repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'  # pick a git hash / tag to point to
    hooks:
    -  id: flake8
       additional_dependencies:
        [
          flake8-annotations,
          flake8-bugbear
        ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -  id: check-merge-conflict

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910-1'
    hooks:
    -  id: mypy

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -  id: isort
       name: isort (python)
       types: [ python ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -  id: no-commit-to-branch
       args:
       - --branch=main